jenkins:
  url: https://jenkins.yourdomain.com
  username: your_name
  token: your_secret_token
  polling_interval: 1_000
  build_processing_ttl: 100
  wireguard_deploy_job:
    uri: /wireguard_deploy_job
    token: job_secret_token

ssl:
  ssl_enabled: yes
  keystore_path: configs/keystore.jks
  keystore_password: secret_password
  key_password: secret_password

bot:
  name: Bot name
  token: 7777777777:secret_token